services:
  db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRES_USER: otm
      POSTGRES_PASSWORD: omguseotm
      POSTGRES_DB: otm
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

volumes:
  pgdata:
